version: '{build}'
image: Visual Studio 2017
pull_requests:  
  do_not_increment_build_number: true
branches:  
  only:
  - master
before_build:
  # Display .NET Core version
  - cmd: dotnet --version
nuget:  
  disable_publish_on_pr: true
build_script:  
- # ps: .\Build.ps1
  build_script:
  # output will be in ./artifacts
  - cmd: dotnet pack .\src\Acheve.TestHost -c Release -o ..\..\artifacts
# test: off
test_script:
  # run the unit tests (requires changing into the test directory)
  - cmd: cd tests
  - cmd: dotnet xunit
  - cmd: cd ..
  - cmd: cd samples
    cmd: dotnet xunit
artifacts:  
- path: .\artifacts\**\*.nupkg
  name: NuGet
deploy:  
- provider: NuGet
  name: production
  api_key:
    secure: h3UWALS617QyaXdEZngYSh+tmtha5HtBRW95rWtGX0GcQN3MOVp4ZrML5oHMspQI
  on:
    branch: master
    appveyor_repo_tag: true