version: '{build}'
image: Visual Studio 2017
init:
  - git config --global core.autocrlf true
branches:  
  only:
  - master
before_build:
  # Display .NET Core version
  - cmd: dotnet --version
pull_requests:  
  do_not_increment_build_number: true
nuget:  
  disable_publish_on_pr: true
build_script:  
# ps: .\Build.ps1
  # output will be in ./artifacts
  cmd: dotnet pack .\src\Acheve.TestHost -c Release -o ..\..\artifacts
# test: off
test:
  assemblies:
    only:
      - UnitTests.dll
      - Sample.IntegrationTests.dll
artifacts:  
- path: .\artifacts\**\*.nupkg
  name: NuGet
deploy:  
- provider: NuGet
  name: production
  api_key:
    secure: h3UWALS617QyaXdEZngYSh+tmtha5HtBRW95rWtGX0GcQN3MOVp4ZrML5oHMspQI
  on:
    branch: master
    appveyor_repo_tag: true